Project_budget_name = "ProjectBudget"
Project_limit_amount      = "100.00"
compute_budget_name = "ComputeBudget"
compute_limit_amount      = "60.00"
storage_budget_name = "StorageBudget"
storage_limit_amount      = "40.00"
network_budget_name = "NetworkBudget"
network_limit_amount      = "20.00"